name: Build snippets
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run compile tests
        run: bash test/run_tests.sh
